version: '3.7'

services:
    dev:
        # stdin_open: true # docker run -i
        # tty: true # docker run -t
        container_name: JotunnLib-container
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - '.:/build'
            - '${VALHEIM_INSTALL}:/VHINSTALL'
        environment: 
            - 'VALHEIM_INSTALL:/VHINSTALL'
    prod:
        # stdin_open: true # docker run -i
        # tty: true # docker run -t
        container_name: JotunnLib-container
        build:
            context: .
            dockerfile: Dockerfile.prod
        volumes:
            - '.:/build'
        environment: 
            - 'VALHEIM_INSTALL:/home/steam/VHINSTALL/'