### YamlMime:ManagedReference
items:
- uid: JotunnLib.Entities.PrefabConfig
  commentId: T:JotunnLib.Entities.PrefabConfig
  id: PrefabConfig
  parent: JotunnLib.Entities
  children:
  - JotunnLib.Entities.PrefabConfig.#ctor(System.String)
  - JotunnLib.Entities.PrefabConfig.#ctor(System.String,System.String)
  - JotunnLib.Entities.PrefabConfig.BasePrefabName
  - JotunnLib.Entities.PrefabConfig.Name
  - JotunnLib.Entities.PrefabConfig.Prefab
  - JotunnLib.Entities.PrefabConfig.Register
  langs:
  - csharp
  - vb
  name: PrefabConfig
  nameWithType: PrefabConfig
  fullName: JotunnLib.Entities.PrefabConfig
  type: Class
  source:
    remote:
      path: JotunnLib/Entities/PrefabConfig.cs
      branch: main
      repo: git@github.com:raduschirliu/valheim-loki-loader
    id: PrefabConfig
    path: Entities/PrefabConfig.cs
    startLine: 4
  assemblies:
  - JotunnLib
  namespace: JotunnLib.Entities
  syntax:
    content: public abstract class PrefabConfig
    content.vb: Public MustInherit Class PrefabConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: JotunnLib.Entities.PrefabConfig.Name
  commentId: P:JotunnLib.Entities.PrefabConfig.Name
  id: Name
  parent: JotunnLib.Entities.PrefabConfig
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: PrefabConfig.Name
  fullName: JotunnLib.Entities.PrefabConfig.Name
  type: Property
  source:
    remote:
      path: JotunnLib/Entities/PrefabConfig.cs
      branch: main
      repo: git@github.com:raduschirliu/valheim-loki-loader
    id: Name
    path: Entities/PrefabConfig.cs
    startLine: 6
  assemblies:
  - JotunnLib
  namespace: JotunnLib.Entities
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: JotunnLib.Entities.PrefabConfig.Name*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: JotunnLib.Entities.PrefabConfig.BasePrefabName
  commentId: P:JotunnLib.Entities.PrefabConfig.BasePrefabName
  id: BasePrefabName
  parent: JotunnLib.Entities.PrefabConfig
  langs:
  - csharp
  - vb
  name: BasePrefabName
  nameWithType: PrefabConfig.BasePrefabName
  fullName: JotunnLib.Entities.PrefabConfig.BasePrefabName
  type: Property
  source:
    remote:
      path: JotunnLib/Entities/PrefabConfig.cs
      branch: main
      repo: git@github.com:raduschirliu/valheim-loki-loader
    id: BasePrefabName
    path: Entities/PrefabConfig.cs
    startLine: 7
  assemblies:
  - JotunnLib
  namespace: JotunnLib.Entities
  syntax:
    content: public string BasePrefabName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property BasePrefabName As String
  overload: JotunnLib.Entities.PrefabConfig.BasePrefabName*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: JotunnLib.Entities.PrefabConfig.Prefab
  commentId: P:JotunnLib.Entities.PrefabConfig.Prefab
  id: Prefab
  parent: JotunnLib.Entities.PrefabConfig
  langs:
  - csharp
  - vb
  name: Prefab
  nameWithType: PrefabConfig.Prefab
  fullName: JotunnLib.Entities.PrefabConfig.Prefab
  type: Property
  source:
    remote:
      path: JotunnLib/Entities/PrefabConfig.cs
      branch: main
      repo: git@github.com:raduschirliu/valheim-loki-loader
    id: Prefab
    path: Entities/PrefabConfig.cs
    startLine: 8
  assemblies:
  - JotunnLib
  namespace: JotunnLib.Entities
  syntax:
    content: public GameObject Prefab { get; set; }
    parameters: []
    return:
      type: UnityEngine.GameObject
    content.vb: Public Property Prefab As GameObject
  overload: JotunnLib.Entities.PrefabConfig.Prefab*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: JotunnLib.Entities.PrefabConfig.#ctor(System.String)
  commentId: M:JotunnLib.Entities.PrefabConfig.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: JotunnLib.Entities.PrefabConfig
  langs:
  - csharp
  - vb
  name: PrefabConfig(String)
  nameWithType: PrefabConfig.PrefabConfig(String)
  fullName: JotunnLib.Entities.PrefabConfig.PrefabConfig(System.String)
  type: Constructor
  source:
    remote:
      path: JotunnLib/Entities/PrefabConfig.cs
      branch: main
      repo: git@github.com:raduschirliu/valheim-loki-loader
    id: .ctor
    path: Entities/PrefabConfig.cs
    startLine: 10
  assemblies:
  - JotunnLib
  namespace: JotunnLib.Entities
  syntax:
    content: public PrefabConfig(string name)
    parameters:
    - id: name
      type: System.String
    content.vb: Public Sub New(name As String)
  overload: JotunnLib.Entities.PrefabConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: JotunnLib.Entities.PrefabConfig.#ctor(System.String,System.String)
  commentId: M:JotunnLib.Entities.PrefabConfig.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: JotunnLib.Entities.PrefabConfig
  langs:
  - csharp
  - vb
  name: PrefabConfig(String, String)
  nameWithType: PrefabConfig.PrefabConfig(String, String)
  fullName: JotunnLib.Entities.PrefabConfig.PrefabConfig(System.String, System.String)
  type: Constructor
  source:
    remote:
      path: JotunnLib/Entities/PrefabConfig.cs
      branch: main
      repo: git@github.com:raduschirliu/valheim-loki-loader
    id: .ctor
    path: Entities/PrefabConfig.cs
    startLine: 15
  assemblies:
  - JotunnLib
  namespace: JotunnLib.Entities
  syntax:
    content: public PrefabConfig(string name, string baseName)
    parameters:
    - id: name
      type: System.String
    - id: baseName
      type: System.String
    content.vb: Public Sub New(name As String, baseName As String)
  overload: JotunnLib.Entities.PrefabConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: JotunnLib.Entities.PrefabConfig.Register
  commentId: M:JotunnLib.Entities.PrefabConfig.Register
  id: Register
  parent: JotunnLib.Entities.PrefabConfig
  langs:
  - csharp
  - vb
  name: Register()
  nameWithType: PrefabConfig.Register()
  fullName: JotunnLib.Entities.PrefabConfig.Register()
  type: Method
  source:
    remote:
      path: JotunnLib/Entities/PrefabConfig.cs
      branch: main
      repo: git@github.com:raduschirliu/valheim-loki-loader
    id: Register
    path: Entities/PrefabConfig.cs
    startLine: 21
  assemblies:
  - JotunnLib
  namespace: JotunnLib.Entities
  syntax:
    content: public abstract void Register()
    content.vb: Public MustOverride Sub Register
  overload: JotunnLib.Entities.PrefabConfig.Register*
  modifiers.csharp:
  - public
  - abstract
  modifiers.vb:
  - Public
  - MustOverride
references:
- uid: JotunnLib.Entities
  commentId: N:JotunnLib.Entities
  name: JotunnLib.Entities
  nameWithType: JotunnLib.Entities
  fullName: JotunnLib.Entities
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: JotunnLib.Entities.PrefabConfig.Name*
  commentId: Overload:JotunnLib.Entities.PrefabConfig.Name
  name: Name
  nameWithType: PrefabConfig.Name
  fullName: JotunnLib.Entities.PrefabConfig.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: JotunnLib.Entities.PrefabConfig.BasePrefabName*
  commentId: Overload:JotunnLib.Entities.PrefabConfig.BasePrefabName
  name: BasePrefabName
  nameWithType: PrefabConfig.BasePrefabName
  fullName: JotunnLib.Entities.PrefabConfig.BasePrefabName
- uid: JotunnLib.Entities.PrefabConfig.Prefab*
  commentId: Overload:JotunnLib.Entities.PrefabConfig.Prefab
  name: Prefab
  nameWithType: PrefabConfig.Prefab
  fullName: JotunnLib.Entities.PrefabConfig.Prefab
- uid: UnityEngine.GameObject
  commentId: T:UnityEngine.GameObject
  parent: UnityEngine
  isExternal: true
  name: GameObject
  nameWithType: GameObject
  fullName: UnityEngine.GameObject
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: JotunnLib.Entities.PrefabConfig.#ctor*
  commentId: Overload:JotunnLib.Entities.PrefabConfig.#ctor
  name: PrefabConfig
  nameWithType: PrefabConfig.PrefabConfig
  fullName: JotunnLib.Entities.PrefabConfig.PrefabConfig
- uid: JotunnLib.Entities.PrefabConfig.Register*
  commentId: Overload:JotunnLib.Entities.PrefabConfig.Register
  name: Register
  nameWithType: PrefabConfig.Register
  fullName: JotunnLib.Entities.PrefabConfig.Register
